spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budget_tracker
    username: budget_tracker_api
    password: Budg37#Tr4ck3r#4p1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  audit:
    enabled: true
    default-user: ${spring.datasource.username}